### ISSUE TITLE
examples doesn't compile with latest Windows development environment

### ISSUE THREAD

**Issue by ik1ne** [wravery/webview2-rs#35]
```text
PS C:\Users\ik1ne\Downloads\webview2-rs-main> cargo build --examples
   Compiling serde v1.0.219
   Compiling serde_json v1.0.140
   Compiling thiserror v2.0.12
   Compiling webview2-com-macros v0.8.0 (C:\Users\ik1ne\Downloads\webview2-rs-main\crates\callback-macros)
   Compiling windows v0.61.1
   Compiling webview2-com-sys v0.37.0 (C:\Users\ik1ne\Downloads\webview2-rs-main\crates\bindings)
   Compiling webview2-com v0.37.0 (C:\Users\ik1ne\Downloads\webview2-rs-main\crates\webview2-com)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\ik1ne\\AppData\\Local\\Temp\\rustcyZby2K\\symbols.o" "<90 object files omitted>" "C:\\Users\\ik1ne\\Downloads\\webview2-rs-main\\target\\debug\\deps/{libwebview2_com-efffbf8843fa4861.rlib,libwebview2_com_sys-6181eeaa5e04737d.rlib,libwindows-cadef340a7af20e5.rlib,libwindows_core-50fac82ce1194a4b.rlib,libwindows_strings-f6aa4139ce9371d4.rlib,libwindows_result-d70826bf967d69b9.rlib,libwindows_link-c671848fa1bbbd80.rlib,libserde_json-be2e67fb6593f8ee.rlib,libmemchr-d67693182891beb8.rlib,libitoa-82e50a6d74a7b471.rlib,libryu-d2a7ab7791ce36e4.rlib,libserde-2e7e604745c3d340.rlib}.rlib" "<sysroot>\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib/{libstd-*,libpanic_unwind-*,libwindows_targets-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libunwind-*,libcfg_if-*,liballoc-*,librustc_std_workspace_core-*,libcore-*,libcompiler_builtins-*}.rlib" "kernel32.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "dbghelp.lib" "/defaultlib:msvcrt" "/NXCOMPAT" "/LIBPATH:C:\\Users\\ik1ne\\Downloads\\webview2-rs-main\\target\\debug\\build\\webview2-com-sys-5c846d0956fe2d92\\out\\x64" "/OUT:C:\\Users\\ik1ne\\Downloads\\webview2-rs-main\\target\\debug\\examples\\sample.exe" "/SUBSYSTEM:windows" "/ENTRY:mainCRTStartup" "/OPT:REF,NOICF" "/DEBUG" "/PDBALTPATH:%_PDB%" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\libstd.natvis" "/NATVIS:C:\\Users\\ik1ne\\AppData\\Local\\Temp\\rustcyZby2K\\sample-0.natvis" "/NATVIS:C:\\Users\\ik1ne\\AppData\\Local\\Temp\\rustcyZby2K\\sample-1.natvis" "/NATVIS:C:\\Users\\ik1ne\\AppData\\Local\\Temp\\rustcyZby2K\\sample-2.natvis"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_impl.obj) : error LNK2019: unresolved external symbol __imp_EventRegister referenced in function "long __cdecl embedded_browser_webview::internal::`anonymous namespace'::TryCreateWebViewEnvironment(struct internal::A0xF367DDF2::WEBVIEW2_ENVIRONMENT_PARAMS,struct ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler *)" (?TryCreateWebViewEnvironment@?A0xF367DDF2@internal@embedded_browser_webview@@YAJUWEBVIEW2_ENVIRONMENT_PARAMS@12@PEAUICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler@@@Z)␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_impl.obj) : error LNK2019: unresolved external symbol __imp_EventSetInformation referenced in function "long __cdecl embedded_browser_webview::internal::`anonymous namespace'::TryCreateWebViewEnvironment(struct internal::A0xF367DDF2::WEBVIEW2_ENVIRONMENT_PARAMS,struct ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler *)" (?TryCreateWebViewEnvironment@?A0xF367DDF2@internal@embedded_browser_webview@@YAJUWEBVIEW2_ENVIRONMENT_PARAMS@12@PEAUICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler@@@Z)␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_impl.obj) : error LNK2019: unresolved external symbol __imp_EventWriteTransfer referenced in function "long __cdecl embedded_browser_webview::internal::`anonymous namespace'::TryCreateWebViewEnvironment(struct internal::A0xF367DDF2::WEBVIEW2_ENVIRONMENT_PARAMS,struct ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler *)" (?TryCreateWebViewEnvironment@?A0xF367DDF2@internal@embedded_browser_webview@@YAJUWEBVIEW2_ENVIRONMENT_PARAMS@12@PEAUICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler@@@Z)␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_impl.obj) : error LNK2019: unresolved external symbol __imp_EventUnregister referenced in function "long __cdecl embedded_browser_webview::internal::`anonymous namespace'::TryCreateWebViewEnvironment(struct internal::A0xF367DDF2::WEBVIEW2_ENVIRONMENT_PARAMS,struct ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler *)" (?TryCreateWebViewEnvironment@?A0xF367DDF2@internal@embedded_browser_webview@@YAJUWEBVIEW2_ENVIRONMENT_PARAMS@12@PEAUICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler@@@Z)␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_impl.obj) : error LNK2019: unresolved external symbol __imp_RegOpenKeyExW referenced in function "bool __cdecl embedded_browser_webview::internal::`anonymous namespace'::FindInstalledClientDllForChannel(wchar_t const *,bool,bool,class internal::A0xF367DDF2::SimpleString *,class internal::A0xF367DDF2::SimpleString *)" (?FindInstalledClientDllForChannel@?A0xF367DDF2@internal@embedded_browser_webview@@YA_NPEB_W_N1PEAVSimpleString@12@2@Z)␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_override.obj) : error LNK2001: unresolved external symbol __imp_RegOpenKeyExW␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_impl.obj) : error LNK2019: unresolved external symbol __imp_RegQueryValueExW referenced in function "bool __cdecl embedded_browser_webview::internal::`anonymous namespace'::FindInstalledClientDllForChannel(wchar_t const *,bool,bool,class internal::A0xF367DDF2::SimpleString *,class internal::A0xF367DDF2::SimpleString *)" (?FindInstalledClientDllForChannel@?A0xF367DDF2@internal@embedded_browser_webview@@YA_NPEB_W_N1PEAVSimpleString@12@2@Z)␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_impl.obj) : error LNK2019: unresolved external symbol __imp_RegCloseKey referenced in function "bool __cdecl embedded_browser_webview::internal::`anonymous namespace'::FindInstalledClientDllForChannel(wchar_t const *,bool,bool,class internal::A0xF367DDF2::SimpleString *,class internal::A0xF367DDF2::SimpleString *)" (?FindInstalledClientDllForChannel@?A0xF367DDF2@internal@embedded_browser_webview@@YA_NPEB_W_N1PEAVSimpleString@12@2@Z)␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_override.obj) : error LNK2001: unresolved external symbol __imp_RegCloseKey␍
          libwebview2_com_sys-6181eeaa5e04737d.rlib(loader_override.obj) : error LNK2019: unresolved external symbol __imp_RegGetValueW referenced in function "bool __cdecl embedded_browser_webview::internal::`anonymous namespace'::ReadOverrideFromRegistry(struct HKEY__ *,struct HKEY__ *,wchar_t const *,wchar_t const * *,class internal::A0x7D832B36::SimpleString *,enum internal::A0x7D832B36::WEBVIEW2_RELEASE_CHANNEL_PREFERENCE *,enum COREWEBVIEW2_RELEASE_CHANNELS *,bool *,bool *)" (?ReadOverrideFromRegistry@?A0x7D832B36@internal@embedded_browser_webview@@YA_NPEAUHKEY__@@0PEB_WPEAPEB_WPEAVSimpleString@12@PEAW4WEBVIEW2_RELEASE_CHANNEL_PREFERENCE@12@PEAW4COREWEBVIEW2_RELEASE_CHANNELS@@PEA_N6@Z)␍
          C:\Users\ik1ne\Downloads\webview2-rs-main\target\debug\examples\sample.exe : fatal error LNK1120: 8 unresolved externals␍


error: could not compile `webview2-com` (example "sample") due to 1 previous error
```

Hi, the examples was compiling about a month ago but after reinstalling the Windows(and windows sdk), this error shows up.
I have checked that AdvAPI32.Lib` exists in `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\AdvAPI32.Lib` and even tried building it with Developer Command Prompt(which makes LIB envvar set), but it still doesn't compile.

I'm not sure what changes made this compile failure - if you can tell me where to check it I would appreciate it.

**Comment by ik1ne** [comment]
Upon further inspection, I realized that the examples build fine on rustc 1.86.0. It seems that rustc 1.87.0 removed implicit linkage of advapi32(https://github.com/rust-lang/rust/pull/138233)

**Comment by wravery** [comment]
Thanks! I made a slightly different fix, but it should work now.
